name: "Construir Aplicaci贸n"

on: [push]

jobs:
  build:
    name: "Construir para Producci贸n"
    runs-on: ubuntu-latest

    steps:
      - name: "Descargar el c贸digo"
        uses: actions/checkout@v4

      - name: "Configurar Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: "Instalar dependencias"
        run: npm install

      - name: "Construir la aplicaci贸n con Vite"
        run: npm run build